#For full documentation of the parameters in this file, and a list of all the
#parameters available for TrajectoryPlannerROS, please see
#http://www.ros.org/wiki/base_local_planner
TrajectoryPlannerROS:
  #Set the acceleration limits of the robot
  acc_lim_th: 3.0 # default:3.2
  acc_lim_x: 2.0  # default:2.5
  acc_lim_y: 0.0  # default:2.5  zero for a differential drive robot

  #Set the velocity limits of the robot
  max_vel_x: 0.2   #Tank_Black_Swan default 0.65
  min_vel_x: 0.05  #TankTB400  default 0.1
  max_vel_y: 0.0   # zero for a differential drive robot default X
  min_vel_y: 0.0   # zdefault X

  max_vel_theta: 0.5 #Tank_Black_Swan  default X
  min_vel_theta: -0.5 #Tank_Black_Swan  default X

  min_in_place_vel_theta: 0.5       #TankTB400  default X
  min_in_place_rotational_vel: 0.5  #TankTB400  default X


# max_rotational_vel: 1.0
# min_in_place_rotational_vel: 0.4


  #The velocity the robot will command when trying to escape from a stuck situation
  escape_vel: -0.1
  
  #For this example, we'll use a holonomic robot
  holonomic_robot: false #TankTB400  default: true  

  #Since we're using a holonomic robot, we'll set the set of y velocities it will sample
#y_vels: [-0.3, -0.1, 0.1, -0.3]  

  #Set the tolerance on achieving a goal
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05

  #We'll configure how long and with what granularity we'll forward simulate trajectories
  sim_time: 2.5   #TankTB400  default 1.7 
  sim_granularity: 0.025
  vx_samples: 20 #TankTB400  default: 3
  vtheta_samples: 20

  #Parameters for scoring trajectories
#goal_distance_bias: 0.8 
#path_distance_bias: 0.6 

  pdist_scale: 1.6 # max is 5
  gdist_scale: 0.6 # max is 5


  occdist_scale: 0.01
  heading_lookahead: 0.325

  #We'll use the Dynamic Window Approach to control instead of Trajectory Rollout for this example
  dwa: true

  #How far the robot must travel before oscillation flags are reset
  oscillation_reset_dist: 0.05

  #Eat up the plan as the robot moves along it
  prune_plan: true
