footprint: [[-0.19, -0.12], [-0.19, 0.12], [0.19, 0.12], [0.19, -0.12]]
footprint_padding: 0.02
#robot_radius: 0.38
#robot_radius: ir_of_robot
inflation_layer:
  inflation_radius: 0.05 # 2xfootprint, it helps to keep the global planned path farther from obstacles
transform_tolerance: 2



